name: Add release label to PR and linked issues when PR gets merged

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  add-release-label:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - uses: endriApp/action-checkout-and-setup@v1
        with:
          is-high-risk-environment: false
          fetch-depth: 0
          skip-allow-scripts: true
          yarn-custom-url: ${{ vars.YARN_URL }}

      - id: get-next-semver-version
        env:
          FORCE_NEXT_SEMVER_VERSION: ${{ vars.FORCE_NEXT_SEMVER_VERSION }}
        run : ./development/get-next-semver-version.sh $FORCE_NEXT_SEMVER_VERSION

      - env :
         RELEASE_LABEL_TOKEN : ${{ secrets.RELEASE_LABEL_TOKEN }}
         NEXT_SEMVER_VERSION : ${{ steps.get-next-semver-version.outputs.NEXT_SEMVER_VERSION }}
       run : yarn run add-release-label-to-pr-and-linked-issues
